using Microsoft.Data.SqlClient;
using System.Data;

namespace Day_10_DisconnectedArch
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string connection = "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=DAC;Integrated Security=True";

            SqlConnection conn = new SqlConnection(connection);

            #region Select
            //SqlDataAdapter adapter = new SqlDataAdapter("select * from emp", conn);
            //adapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            //DataSet dataSet = new DataSet();

            //adapter.Fill(dataSet, "emp");

            //foreach (DataRow row in dataSet.Tables["emp"].Rows)
            //{
            //    int id = Convert.ToInt32(row["ID"]);
            //    string? name = Convert.ToString(row["Name"]);
            //    string? address = Convert.ToString(row["Address"]);

            //    Console.WriteLine($"ID : {id}, Name : {name}, Address : {address}");
            //} 
            #endregion

            #region Insert
            //SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM EMP", conn);

            //da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            //SqlCommandBuilder builder = new SqlCommandBuilder(da);

            //DataSet ds = new DataSet();
            //da.Fill(ds, "Emp");


            //Console.WriteLine("Enter Name:");
            //string nm = Console.ReadLine();
            //Console.WriteLine("Enter Address:");
            //string add = Console.ReadLine();

            //DataRow newRow = ds.Tables["Emp"].NewRow();
            //newRow["Name"] = nm;
            //newRow["Address"] = add;

            //ds.Tables["Emp"].Rows.Add(newRow);

            //da.Update(ds, "Emp");//Insert Query is generated by CommandBuilder
            //Console.WriteLine("Record inserted!"); 
            #endregion

        }
    }
}
